apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: db
  name: db
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: db
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.service: db
    spec:
      containers:
        - env:
            - name: LC_ALL
              value: C.UTF-8
            - name: POSTGRES_DB
              value: gestion
            - name: POSTGRES_PASSWORD
              value: Secret
            - name: POSTGRES_USER
              value: postgres
          image: postgres:alpine
          livenessProbe:
            exec:
              command:
                - pg_isready --username=postgres && psql --username=postgres --list
            failureThreshold: 20
            timeoutSeconds: 10
          name: postgresdb
          ports:
            - containerPort: 5432
          resources: {}
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: dbdata
            - mountPath: /backups
              name: dbbackup
      restartPolicy: Always
      volumes:
        - name: dbdata
          persistentVolumeClaim:
            claimName: dbdata
        - name: dbbackup
          persistentVolumeClaim:
            claimName: dbbackup
status: {}
